// src/App.vue
<script setup>
import { computed, ref } from "vue";
const TRAFFIC_LIGHTS = ["red", "orange", "green"];
const lightIndex = ref(0);

const light = computed(() => TRAFFIC_LIGHTS[lightIndex.value]);

function nextLight() {
  if (lightIndex.value + 1 > TRAFFIC_LIGHTS.length - 1) {
    lightIndex.value = 0;
  } else {
    lightIndex.value++;
  }
}
</script>

<template>
  <button @click="nextLight">Next light</button>
  <p>Light is: {{ light }}</p>
  <p>
    You must
    <span v-if="light === 'red'">STOP</span>
    <span v-else-if="light === 'orange'">SLOW DOWN</span>
    <span v-else-if="light === 'green'">GO</span>
  </p>
</template>

// src/App.component.ts
/* eslint-disable max-classes-per-file */
import { Component, Pipe, PipeTransform } from "@angular/core";

const TRAFFIC_LIGHTS = ["red", "orange", "green"];

@Pipe({
  name: "light",
})
export class TrafficLightPipe implements PipeTransform {
  transform(value: number): string {
    return TRAFFIC_LIGHTS[value];
  }
}

@Component({
  selector: "app-trafficlight",
  templateUrl: "./trafficlight.component.html",
})
export class TrafficlightComponent {
  lightIndex: number = 0;

  nextLight(): void {
    if (this.lightIndex + 1 > TRAFFIC_LIGHTS.length - 1) {
      this.lightIndex = 0;
    } else {
      this.lightIndex += 1;
    }
  }
}

<button (click)="nextLight()">Next light</button>
<p>Light is: {{ lightIndex | light }}</p>
<p>
  You must
  <span *ngIf="(lightIndex | light) === 'red'">STOP</span>
  <span *ngIf="(lightIndex | light) === 'orange'">SLOW DOWN</span>
  <span *ngIf="(lightIndex | light) === 'green'">GO</span>
</p>
